name: Pylint

on:
  workflow_dispatch:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Get newest code and run pylint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Run pylint
      # --fail-under=9.25 - fail if score is below 9.25
      # --fail-on=E - fail if there were errors, regardless of the score
      # --reports=y - print a report at the end
      run: |
        python3 -m pylint --version
        python3 -m pylint --fail-under=9.25 --fail-on=E --reports=y `find . -type d \( -path ./venv -o -path ./core_lib \) -prune -o -type f | grep .py$ | xargs`
